2025-02-24 07:39:06 [ERROR]: Cannot read properties of undefined (reading 'startsWith')
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at Text_DocumentLoaders.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/documentloaders/Text/Text.js:76:27)
    at buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:468:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async executeUpsert (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:137:28)
    at async upsertVector (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:237:28)
    at async Object.upsertVectorMiddleware (/usr/local/lib/node_modules/flowise/dist/services/vectors/index.js:9:16)
    at async createInternalUpsert (/usr/local/lib/node_modules/flowise/dist/controllers/vectors/index.js:28:29)
2025-02-24 07:39:06 [ERROR]: [server]: Error: TypeError: Cannot read properties of undefined (reading 'startsWith')
Error: TypeError: Cannot read properties of undefined (reading 'startsWith')
    at buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:517:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async executeUpsert (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:137:28)
    at async upsertVector (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:237:28)
    at async Object.upsertVectorMiddleware (/usr/local/lib/node_modules/flowise/dist/services/vectors/index.js:9:16)
    at async createInternalUpsert (/usr/local/lib/node_modules/flowise/dist/controllers/vectors/index.js:28:29)
2025-02-24 07:40:49 [ERROR]: Cannot read properties of undefined (reading 'startsWith')
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at Text_DocumentLoaders.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/documentloaders/Text/Text.js:76:27)
    at buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:468:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async executeUpsert (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:137:28)
    at async upsertVector (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:237:28)
    at async Object.upsertVectorMiddleware (/usr/local/lib/node_modules/flowise/dist/services/vectors/index.js:9:16)
    at async createInternalUpsert (/usr/local/lib/node_modules/flowise/dist/controllers/vectors/index.js:28:29)
2025-02-24 07:40:49 [ERROR]: [server]: Error: TypeError: Cannot read properties of undefined (reading 'startsWith')
Error: TypeError: Cannot read properties of undefined (reading 'startsWith')
    at buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:517:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async executeUpsert (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:137:28)
    at async upsertVector (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:237:28)
    at async Object.upsertVectorMiddleware (/usr/local/lib/node_modules/flowise/dist/services/vectors/index.js:9:16)
    at async createInternalUpsert (/usr/local/lib/node_modules/flowise/dist/controllers/vectors/index.js:28:29)
2025-02-24 07:42:02 [ERROR]: Cannot read properties of undefined (reading 'startsWith')
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at Text_DocumentLoaders.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/documentloaders/Text/Text.js:76:27)
    at buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:468:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async executeUpsert (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:137:28)
    at async upsertVector (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:237:28)
    at async Object.upsertVectorMiddleware (/usr/local/lib/node_modules/flowise/dist/services/vectors/index.js:9:16)
    at async createInternalUpsert (/usr/local/lib/node_modules/flowise/dist/controllers/vectors/index.js:28:29)
2025-02-24 07:42:02 [ERROR]: [server]: Error: TypeError: Cannot read properties of undefined (reading 'startsWith')
Error: TypeError: Cannot read properties of undefined (reading 'startsWith')
    at buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:517:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async executeUpsert (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:137:28)
    at async upsertVector (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:237:28)
    at async Object.upsertVectorMiddleware (/usr/local/lib/node_modules/flowise/dist/services/vectors/index.js:9:16)
    at async createInternalUpsert (/usr/local/lib/node_modules/flowise/dist/controllers/vectors/index.js:28:29)
2025-02-24 07:48:38 [ERROR]: [server]: Error: graph[currentNode] is not iterable
TypeError: graph[currentNode] is not iterable
    at getAllConnectedNodes (/usr/local/lib/node_modules/flowise/dist/utils/index.js:219:37)
    at executeUpsert (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:126:54)
    at upsertVector (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:237:60)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.upsertVectorMiddleware (/usr/local/lib/node_modules/flowise/dist/services/vectors/index.js:9:16)
    at async createInternalUpsert (/usr/local/lib/node_modules/flowise/dist/controllers/vectors/index.js:28:29)
2025-02-24 07:49:22 [ERROR]: [server]: Error: graph[currentNode] is not iterable
TypeError: graph[currentNode] is not iterable
    at getAllConnectedNodes (/usr/local/lib/node_modules/flowise/dist/utils/index.js:219:37)
    at executeUpsert (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:126:54)
    at upsertVector (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:237:60)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.upsertVectorMiddleware (/usr/local/lib/node_modules/flowise/dist/services/vectors/index.js:9:16)
    at async createInternalUpsert (/usr/local/lib/node_modules/flowise/dist/controllers/vectors/index.js:28:29)
2025-02-24 07:56:00 [ERROR]: [server]: Error: graph[currentNode] is not iterable
TypeError: graph[currentNode] is not iterable
    at getAllConnectedNodes (/usr/local/lib/node_modules/flowise/dist/utils/index.js:219:37)
    at executeUpsert (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:126:54)
    at upsertVector (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:237:60)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.upsertVectorMiddleware (/usr/local/lib/node_modules/flowise/dist/services/vectors/index.js:9:16)
    at async createInternalUpsert (/usr/local/lib/node_modules/flowise/dist/controllers/vectors/index.js:28:29)
2025-02-24 07:57:41 [ERROR]: Cannot read properties of undefined (reading 'startsWith')
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at Text_DocumentLoaders.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/documentloaders/Text/Text.js:76:27)
    at buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:468:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async executeUpsert (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:137:28)
    at async upsertVector (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:237:28)
    at async Object.upsertVectorMiddleware (/usr/local/lib/node_modules/flowise/dist/services/vectors/index.js:9:16)
    at async createInternalUpsert (/usr/local/lib/node_modules/flowise/dist/controllers/vectors/index.js:28:29)
2025-02-24 07:57:41 [ERROR]: [server]: Error: TypeError: Cannot read properties of undefined (reading 'startsWith')
Error: TypeError: Cannot read properties of undefined (reading 'startsWith')
    at buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:517:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async executeUpsert (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:137:28)
    at async upsertVector (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:237:28)
    at async Object.upsertVectorMiddleware (/usr/local/lib/node_modules/flowise/dist/services/vectors/index.js:9:16)
    at async createInternalUpsert (/usr/local/lib/node_modules/flowise/dist/controllers/vectors/index.js:28:29)
2025-02-25 01:37:03 [ERROR]: Expected a Runnable, function or object.
Instead got an unsupported type.
Error: Expected a Runnable, function or object.
Instead got an unsupported type.
    at _coerceToRunnable (/usr/src/node_modules/.pnpm/@langchain+core@0.3.37_openai@4.82.0_encoding@0.1.13_ws@8.16.0_bufferutil@4.0.8_utf-8-validate@6.0.4__zod@3.22.4_/node_modules/@langchain/core/dist/runnables/base.cjs:2105:15)
    at RunnableBinding.pipe (/usr/src/node_modules/.pnpm/@langchain+core@0.3.37_openai@4.82.0_encoding@0.1.13_ws@8.16.0_bufferutil@4.0.8_utf-8-validate@6.0.4__zod@3.22.4_/node_modules/@langchain/core/dist/runnables/base.cjs:362:19)
    at createRetrieverChain (/usr/src/packages/components/dist/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.js:256:53)
    at createChain (/usr/src/packages/components/dist/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.js:287:28)
    at ConversationalRetrievalQAChain_Chains.init (/usr/src/packages/components/dist/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.js:133:29)
    at buildFlow (/usr/src/packages/server/dist/utils/index.js:468:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async executeFlow (/usr/src/packages/server/dist/utils/buildChatflow.js:290:28)
    at async utilBuildChatflow (/usr/src/packages/server/dist/utils/buildChatflow.js:644:28)
    at async createAndStreamInternalPrediction (/usr/src/packages/server/dist/controllers/internal-predictions/index.js:38:29)
2025-02-25 01:37:03 [ERROR]: [server]: Error: Error: Expected a Runnable, function or object.
Instead got an unsupported type.
Error: Error: Expected a Runnable, function or object.
Instead got an unsupported type.
    at buildFlow (/usr/src/packages/server/dist/utils/index.js:517:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async executeFlow (/usr/src/packages/server/dist/utils/buildChatflow.js:290:28)
    at async utilBuildChatflow (/usr/src/packages/server/dist/utils/buildChatflow.js:644:28)
    at async createAndStreamInternalPrediction (/usr/src/packages/server/dist/controllers/internal-predictions/index.js:38:29)
2025-02-25 07:46:43 [ERROR]: ❌ [server]: Error during Data Source initialization: connect ECONNREFUSED 172.19.0.7:5432
Error: connect ECONNREFUSED 172.19.0.7:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)
2025-02-25 07:47:31 [ERROR]: ❌[server]: Flowise Server shut down error: TypeError: Cannot read properties of undefined (reading 'flush')
2025-02-25 07:48:44 [ERROR]: Expected a Runnable, function or object.
Instead got an unsupported type.
Error: Expected a Runnable, function or object.
Instead got an unsupported type.
    at _coerceToRunnable (/usr/src/node_modules/.pnpm/@langchain+core@0.3.37_openai@4.82.0_encoding@0.1.13_ws@8.16.0_bufferutil@4.0.8_utf-8-validate@6.0.4__zod@3.22.4_/node_modules/@langchain/core/dist/runnables/base.cjs:2105:15)
    at RunnableBinding.pipe (/usr/src/node_modules/.pnpm/@langchain+core@0.3.37_openai@4.82.0_encoding@0.1.13_ws@8.16.0_bufferutil@4.0.8_utf-8-validate@6.0.4__zod@3.22.4_/node_modules/@langchain/core/dist/runnables/base.cjs:362:19)
    at createRetrieverChain (/usr/src/packages/components/dist/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.js:256:53)
    at createChain (/usr/src/packages/components/dist/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.js:287:28)
    at ConversationalRetrievalQAChain_Chains.init (/usr/src/packages/components/dist/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.js:133:29)
    at buildFlow (/usr/src/packages/server/dist/utils/index.js:468:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async executeFlow (/usr/src/packages/server/dist/utils/buildChatflow.js:290:28)
    at async utilBuildChatflow (/usr/src/packages/server/dist/utils/buildChatflow.js:644:28)
    at async createAndStreamInternalPrediction (/usr/src/packages/server/dist/controllers/internal-predictions/index.js:38:29)
2025-02-25 07:48:44 [ERROR]: [server]: Error: Error: Expected a Runnable, function or object.
Instead got an unsupported type.
Error: Error: Expected a Runnable, function or object.
Instead got an unsupported type.
    at buildFlow (/usr/src/packages/server/dist/utils/index.js:517:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async executeFlow (/usr/src/packages/server/dist/utils/buildChatflow.js:290:28)
    at async utilBuildChatflow (/usr/src/packages/server/dist/utils/buildChatflow.js:644:28)
    at async createAndStreamInternalPrediction (/usr/src/packages/server/dist/controllers/internal-predictions/index.js:38:29)
2025-02-25 07:49:25 [ERROR]: [server]: Error: graph[currentNode] is not iterable
TypeError: graph[currentNode] is not iterable
    at getAllConnectedNodes (/usr/src/packages/server/dist/utils/index.js:219:37)
    at executeUpsert (/usr/src/packages/server/dist/utils/upsertVector.js:126:54)
    at upsertVector (/usr/src/packages/server/dist/utils/upsertVector.js:237:60)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.upsertVectorMiddleware (/usr/src/packages/server/dist/services/vectors/index.js:9:16)
    at async createInternalUpsert (/usr/src/packages/server/dist/controllers/vectors/index.js:28:29)
2025-02-25 07:49:28 [ERROR]: [server]: Error: graph[currentNode] is not iterable
TypeError: graph[currentNode] is not iterable
    at getAllConnectedNodes (/usr/src/packages/server/dist/utils/index.js:219:37)
    at executeUpsert (/usr/src/packages/server/dist/utils/upsertVector.js:126:54)
    at upsertVector (/usr/src/packages/server/dist/utils/upsertVector.js:237:60)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.upsertVectorMiddleware (/usr/src/packages/server/dist/services/vectors/index.js:9:16)
    at async createInternalUpsert (/usr/src/packages/server/dist/controllers/vectors/index.js:28:29)
2025-02-25 07:53:54 [ERROR]: ENOENT: no such file or directory, open '/root/.flowise/storage/7c1d40d1-ef16-4974-9415-4831c2139278/2025학년도 입학전형 시행계획_경민대학교(최종).pdf'
Error: ENOENT: no such file or directory, open '/root/.flowise/storage/7c1d40d1-ef16-4974-9415-4831c2139278/2025학년도 입학전형 시행계획_경민대학교(최종).pdf'
    at Object.openSync (node:fs:574:18)
    at Object.readFileSync (node:fs:453:35)
    at getFileFromStorage (/usr/src/packages/components/dist/src/storageUtils.js:169:29)
    at Pdf_DocumentLoaders.init (/usr/src/packages/components/dist/nodes/documentloaders/Pdf/Pdf.js:136:69)
    at buildFlow (/usr/src/packages/server/dist/utils/index.js:468:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async executeUpsert (/usr/src/packages/server/dist/utils/upsertVector.js:137:28)
    at async upsertVector (/usr/src/packages/server/dist/utils/upsertVector.js:237:28)
    at async Object.upsertVectorMiddleware (/usr/src/packages/server/dist/services/vectors/index.js:9:16)
    at async createInternalUpsert (/usr/src/packages/server/dist/controllers/vectors/index.js:28:29)
2025-02-25 07:53:54 [ERROR]: [server]: Error: Error: ENOENT: no such file or directory, open '/root/.flowise/storage/7c1d40d1-ef16-4974-9415-4831c2139278/2025학년도 입학전형 시행계획_경민대학교(최종).pdf'
Error: Error: ENOENT: no such file or directory, open '/root/.flowise/storage/7c1d40d1-ef16-4974-9415-4831c2139278/2025학년도 입학전형 시행계획_경민대학교(최종).pdf'
    at buildFlow (/usr/src/packages/server/dist/utils/index.js:517:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async executeUpsert (/usr/src/packages/server/dist/utils/upsertVector.js:137:28)
    at async upsertVector (/usr/src/packages/server/dist/utils/upsertVector.js:237:28)
    at async Object.upsertVectorMiddleware (/usr/src/packages/server/dist/services/vectors/index.js:9:16)
    at async createInternalUpsert (/usr/src/packages/server/dist/controllers/vectors/index.js:28:29)
2025-02-25 07:54:28 [ERROR]: Error: Chroma getOrCreateCollection error: ChromaConnectionError: Failed to connect to chromadb. Make sure your server is running and try again. If you are running from a browser, make sure that your chromadb instance is configured to allow requests from the current origin using the CHROMA_SERVER_CORS_ALLOW_ORIGINS environment variable.
Error: Error: Chroma getOrCreateCollection error: ChromaConnectionError: Failed to connect to chromadb. Make sure your server is running and try again. If you are running from a browser, make sure that your chromadb instance is configured to allow requests from the current origin using the CHROMA_SERVER_CORS_ALLOW_ORIGINS environment variable.
    at Chroma_VectorStores.upsert (/usr/src/packages/components/dist/nodes/vectorstores/Chroma/Chroma.js:61:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async buildFlow (/usr/src/packages/server/dist/utils/index.js:441:37)
    at async executeUpsert (/usr/src/packages/server/dist/utils/upsertVector.js:137:28)
    at async upsertVector (/usr/src/packages/server/dist/utils/upsertVector.js:237:28)
    at async Object.upsertVectorMiddleware (/usr/src/packages/server/dist/services/vectors/index.js:9:16)
    at async createInternalUpsert (/usr/src/packages/server/dist/controllers/vectors/index.js:28:29)
2025-02-25 07:54:28 [ERROR]: [server]: Error: Error: Error: Chroma getOrCreateCollection error: ChromaConnectionError: Failed to connect to chromadb. Make sure your server is running and try again. If you are running from a browser, make sure that your chromadb instance is configured to allow requests from the current origin using the CHROMA_SERVER_CORS_ALLOW_ORIGINS environment variable.
Error: Error: Error: Chroma getOrCreateCollection error: ChromaConnectionError: Failed to connect to chromadb. Make sure your server is running and try again. If you are running from a browser, make sure that your chromadb instance is configured to allow requests from the current origin using the CHROMA_SERVER_CORS_ALLOW_ORIGINS environment variable.
    at buildFlow (/usr/src/packages/server/dist/utils/index.js:517:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async executeUpsert (/usr/src/packages/server/dist/utils/upsertVector.js:137:28)
    at async upsertVector (/usr/src/packages/server/dist/utils/upsertVector.js:237:28)
    at async Object.upsertVectorMiddleware (/usr/src/packages/server/dist/services/vectors/index.js:9:16)
    at async createInternalUpsert (/usr/src/packages/server/dist/controllers/vectors/index.js:28:29)
